apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: frontendconfigs.networking.gke.io
spec:
  conversion:
    strategy: None
  group: networking.gke.io
  names:
    kind: FrontendConfig
    listKind: FrontendConfigList
    plural: frontendconfigs
    singular: frontendconfig
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              description: "APIVersion defines the versioned schema of this representation of
                an object. Servers should convert recognized schemas to the
                latest internal value, and may reject unrecognized values. More
                info:
                https://git.k8s.io/community/contributors/devel/sig-architectur\
                e/api-conventions.md#resources"
              type: string
            kind:
              description: "Kind is a string value representing the REST resource this object
                represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info:
                https://git.k8s.io/community/contributors/devel/sig-architectur\
                e/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              description: FrontendConfigSpec is the spec for a FrontendConfig resource
              properties:
                redirectToHttps:
                  description: HttpsRedirectConfig representing the configuration of Https
                    redirects
                  properties:
                    enabled:
                      type: boolean
                    responseCodeName:
                      description: String representing the HTTP response code Options are
                        MOVED_PERMANENTLY_DEFAULT, FOUND, TEMPORARY_REDIRECT, or
                        PERMANENT_REDIRECT
                      type: string
                  required:
                    - enabled
                  type: object
                sslPolicy:
                  type: string
              type: object
            status:
              type: object
          type: object
      served: true
      storage: true
